/**
 * @generated
 * @source b761e4d2e9e509eb8aa8c04c381b46d2308d7e85
 * @date 2026-03-21T17:11:38.550Z
 */
import { z } from 'zod'
/** Zod enum schema for FightProp. */
export const FightPropEnum = z.enum([
  'FIGHT_PROP_ADD_HURT',
  'FIGHT_PROP_ATTACK',
  'FIGHT_PROP_ATTACK_PERCENT',
  'FIGHT_PROP_BASE_ATTACK',
  'FIGHT_PROP_BASE_DEFENSE',
  'FIGHT_PROP_BASE_HP',
  'FIGHT_PROP_CHARGE_EFFICIENCY',
  'FIGHT_PROP_CRITICAL',
  'FIGHT_PROP_CRITICAL_HURT',
  'FIGHT_PROP_DEFENSE',
  'FIGHT_PROP_DEFENSE_PERCENT',
  'FIGHT_PROP_ELEC_ADD_HURT',
  'FIGHT_PROP_ELEC_SUB_HURT',
  'FIGHT_PROP_ELEMENT_MASTERY',
  'FIGHT_PROP_FIRE_ADD_HURT',
  'FIGHT_PROP_FIRE_SUB_HURT',
  'FIGHT_PROP_GRASS_ADD_HURT',
  'FIGHT_PROP_HEALED_ADD',
  'FIGHT_PROP_HEAL_ADD',
  'FIGHT_PROP_HP',
  'FIGHT_PROP_HP_PERCENT',
  'FIGHT_PROP_ICE_ADD_HURT',
  'FIGHT_PROP_NONE',
  'FIGHT_PROP_PHYSICAL_ADD_HURT',
  'FIGHT_PROP_ROCK_ADD_HURT',
  'FIGHT_PROP_SHIELD_COST_MINUS_RATIO',
  'FIGHT_PROP_WATER_ADD_HURT',
  'FIGHT_PROP_WIND_ADD_HURT',
])
/** Type representing FightProp. */
export type FightProp = z.infer<typeof FightPropEnum>
