/**
 * @generated
 * @source b761e4d2e9e509eb8aa8c04c381b46d2308d7e85
 * @date 2026-03-21T17:11:38.550Z
 */
import { z } from 'zod'
/** Zod enum schema for GrowCurve. */
export const GrowCurveEnum = z.enum([
  'GROW_CURVE_ACTIVITY_ATTACK_1',
  'GROW_CURVE_ACTIVITY_ATTACK_2',
  'GROW_CURVE_ACTIVITY_DEFENSE_2',
  'GROW_CURVE_ACTIVITY_HP_1',
  'GROW_CURVE_ACTIVITY_HP_2',
  'GROW_CURVE_ATTACK',
  'GROW_CURVE_ATTACK_101',
  'GROW_CURVE_ATTACK_102',
  'GROW_CURVE_ATTACK_103',
  'GROW_CURVE_ATTACK_104',
  'GROW_CURVE_ATTACK_105',
  'GROW_CURVE_ATTACK_2',
  'GROW_CURVE_ATTACK_201',
  'GROW_CURVE_ATTACK_202',
  'GROW_CURVE_ATTACK_203',
  'GROW_CURVE_ATTACK_204',
  'GROW_CURVE_ATTACK_205',
  'GROW_CURVE_ATTACK_301',
  'GROW_CURVE_ATTACK_302',
  'GROW_CURVE_ATTACK_303',
  'GROW_CURVE_ATTACK_304',
  'GROW_CURVE_ATTACK_305',
  'GROW_CURVE_ATTACK_S4',
  'GROW_CURVE_ATTACK_S5',
  'GROW_CURVE_CRITICAL_101',
  'GROW_CURVE_CRITICAL_201',
  'GROW_CURVE_CRITICAL_301',
  'GROW_CURVE_DEFENDING',
  'GROW_CURVE_DEFENSE',
  'GROW_CURVE_ELEMENT',
  'GROW_CURVE_HP',
  'GROW_CURVE_HP_2',
  'GROW_CURVE_HP_ENVIRONMENT',
  'GROW_CURVE_HP_LITTLEMONSTER',
  'GROW_CURVE_HP_S4',
  'GROW_CURVE_HP_S5',
  'GROW_CURVE_KILL_EXP',
  'GROW_CURVE_MATK',
  'GROW_CURVE_MHP',
  'GROW_CURVE_NONE',
  'GROW_CURVE_STRIKE',
  'GROW_CURVE_STRIKE_HURT',
])
/** Type representing GrowCurve. */
export type GrowCurve = z.infer<typeof GrowCurveEnum>
