/**
 * @generated
 * @source b761e4d2e9e509eb8aa8c04c381b46d2308d7e85
 * @date 2026-03-21T01:00:54.549Z
 */
import { z } from 'zod'
/** Zod enum schema for ProudEffect. */
export const ProudEffectEnum = z.enum([
  'PROUD_EFFECT_COMBINE_MULTIPLY_OUTPUT',
  'PROUD_EFFECT_COMBINE_RETURN_MATERIAL',
  'PROUD_EFFECT_COMBINE_RETURN_SPECIAL_MATERIAL',
  'PROUD_EFFECT_COOK_CAN_NOT_COOK',
  'PROUD_EFFECT_COOK_PERFECT_MULTI_OUTPUT',
  'PROUD_EFFECT_COOK_PROB_MULTI_OUTPUT',
  'PROUD_EFFECT_EXPEDITION_EXTRA_OUTPUT',
  'PROUD_EFFECT_EXPEDITION_SHORTEN_TIME',
  'PROUD_EFFECT_FISHING_EXTRA_OUTPUT',
  'PROUD_EFFECT_FORGE_ADD_EXTRA_PROB',
  'PROUD_EFFECT_FORGE_REDUCE_TIME',
  'PROUD_EFFECT_FORGE_RETURN_MATERIAL',
  'PROUD_EFFECT_FURNITURE_MAKE_RETURN_MATERIAL',
  'PROUD_EFFECT_HIT_TREE_EXTRA_OUTPUT',
  'PROUD_EFFECT_NONE',
  'PROUD_EFFECT_USE_FOOD_PROB_GET_ITEM',
  'PROUD_EFFECT_WEAPON_PROMOTE_REDUCE_SCOIN',
])
/** Type representing ProudEffect. */
export type ProudEffect = z.infer<typeof ProudEffectEnum>
