name: DataTest
permissions:
  contents: read

on:
  schedule:
    - cron: '0 15 * * 1' # every Monday at 15:00 UTC (0:00 JST)
  workflow_dispatch:

jobs:
  AllId:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build
        run: npm run build

      - name: Run test
        run: npm run release-test --test-type="AllId"

  EnkaNetwork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build
        run: npm run build

      - name: Run test
        run: npm run release-test --test-type="EnkaNetwork"

  findMonsterIdByDescribeId:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build
        run: npm run build

      - name: Run test
        run: npm run release-test --test-type="findMonsterIdByDescribeId"
